issue #28 Error for global symbolic variables are assigned 0
fp-analysis/klee pull request #32
Opened 2017-08-10 07:40 UTC by Himeshi

Depends on pull request #31.

2017-08-11 01:06 UTC, domainexpert commented
@Himeshi Is this PR a work in progress not yet ready for merging? In such case I would usually prefix the title with "WIP:" to clarify. Please feel free to assign me as a reviewer when this is ready for review.

2017-08-11 02:28 UTC, Himeshi commented
@domainexpert I think it is ready - any changes you wish to see in this? 

The function `isInStoredError` is implemented in pull request #31 but a quick Google search told me that there is no way to create dependent pull requests.

2017-08-11 04:07 UTC, domainexpert commented
@Himeshi I recommend we continue working on this after #31 is merged.

2017-08-17 02:23 UTC, domainexpert requested changes
@Himeshi Thank you for the good work. After adding new commits, you could rebase with the `master`, as follows:
```
git checkout master
git pull
git checkout issue28
git rebase -i master
```

2017-08-17 02:23 UTC, domainexpert commented on lib/Core/Executor.cpp
> +         ret.error = ConstantExpr::create(0, Expr::Int8);
@Himeshi This PR has some indentation issues. Have you applied clang-format?

2017-08-17 02:23 UTC, domainexpert commented on lib/Core/SymbolicError.h
> +	  return errorState->isInStoredError(address);
@Himeshi Indentation issue here (too many indent spaces).

2017-08-17 02:23 UTC, domainexpert commented on lib/Core/SymbolicError.h
> +	  return errorState->retrieveStoredError(address);
@Himeshi Ditto here.

2017-08-18 02:12 UTC, domainexpert approved these changes

2017-08-18 02:13 UTC, merged