Pretty printing removes array indices #29
fp-analysis/klee pull request #34
Opened 2017-08-12 10:40 UTC by Himeshi

2017-08-17 05:47 UTC, domainexpert requested changes
@Himeshi I think 16-bit and 8-bit cases are not handled.

2017-08-17 05:47 UTC, domainexpert commented on lib/Core/PrettyExpressionBuilder.cpp
> +const std::string array_prefix64 = "__arr64__";
@Himeshi It seems there are missing cases of arrays of 16 bits and 8 bits (byte) here.

2017-08-18 02:25 UTC, domainexpert approved these changes

2017-08-18 02:26 UTC, domainexpert commented
@Himeshi Would you please rebase to master and please let me know how to test that this fix is working?

2017-08-18 03:59 UTC, domainexpert requested changes
@Himeshi Just a tiny thing: the rest looks good to me.

2017-08-18 03:59 UTC, domainexpert commented on lib/Core/PrettyExpressionBuilder.cpp
> +    return array.erase(0, 9) + "[" + so.str() + "]";
@Himeshi The erase range here should be (0, 8).

2017-08-18 04:12 UTC, Himeshi commented
This pull request can be tested with the attached program. Without this code the array indices should be missing in the error expression in the `test000001
[array_test2.pdf](https://github.com/fp-analysis/klee/files/1233257/array_test2.pdf)
.presicion_error` file.

2017-08-18 04:13 UTC, domainexpert approved these changes

2017-08-18 04:15 UTC, domainexpert commented
@Himeshi Awesome work. Thank you!

2017-08-18 04:15 UTC, merged