Issue47 Maintain symbolic expressions containing error for path conditions
fp-analysis/klee pull request #50
Opened 2017-11-04 06:15 UTC by Himeshi

2017-11-06 02:33 UTC, domainexpert requested changes
Some small changes for now, and please rebase with master. I also requested some explanations in various places. It seems relative error is being used, with the assumption that the relative error is <= 1. However, this may not be true: There can be, for example, 200% error. Please correct me if my question is invalid. Do you have an example that I can use to check that the correct error being generated?

2017-11-06 02:33 UTC, domainexpert commented on lib/Core/ErrorState.cpp
> +    ref<Expr> leftMul = MulExpr::create(arguments.at(0).error, lError);
I think here it should be arguments.at(0).value.

2017-11-06 02:33 UTC, domainexpert commented on lib/Core/ErrorState.cpp
> +    ref<Expr> rightMul = MulExpr::create(arguments.at(1).error, rError);
I think here it should be arguments.at(1).value.

2017-11-06 02:33 UTC, domainexpert commented on lib/Core/SeedInfo.cpp
> +                          ConstantExpr::create(1, Expr::Int8));
Why is the error amount here 1?

2017-11-06 02:33 UTC, domainexpert commented on lib/Core/SeedInfo.cpp
> +                          ConstantExpr::create(1, Expr::Int8));
Why is the error here 1?

2017-11-06 02:33 UTC, domainexpert commented on lib/Core/SpecialFunctionHandler.cpp
> +                    ConstantExpr::create(1, Expr::Int8), true);
Why is the error here 1?

2017-11-06 02:33 UTC, domainexpert commented on lib/Core/Executor.cpp
> +        tmp.addConstraint(*pi, ConstantExpr::create(1, Expr::Int8));
Why is the error here 1?

2017-11-06 02:33 UTC, domainexpert commented on lib/Core/SymbolicError.h
> +  void addErrorCondition(ref<Expr> error) {
@Himeshi I prefer renaming of this to addErrorConstraint for uniformity with the rest of the KLEE code.

2017-11-07 04:08 UTC, domainexpert commented
@Himeshi Do you have an example that you used for testing this feature? Just so that I could test it myself.

2017-11-15 09:21 UTC, Himeshi commented
Added a new pull request #56 and therefore closing.

2017-11-15 09:21 UTC, closed without merging